version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run tests
          command: |
            poetry run coverage run -m pytest
            poetry run coverage report
            poetry run coverage html
      
      - store_artifacts:
          path: htmlcov

  publish:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry@1.7.1
      - run:
          name: Build project
          command: poetry build
      - run:
          name: Publish project
          command: poetry publish

workflows:
  build-and-test:
    jobs:
      - build-and-test
      - publish:
          filters:
            tags:
              only: /^([0-9]+\.){2}[0-9]+/
            branches:
              ignore: /.*/
